### ISSUE TITLE
GooglePaymentCardNonce.isNetworkTokenized is always false in sandbox

### ISSUE THREAD

**Issue by francescocervone** [braintree/braintree-android-google-payment#24]
### General information
 * Braintree Android SDK/Library version: 3.17.2
 * Braintree GooglePayment Module version: 3.4.0
 * Environment: Sandbox
 * Android Version and Device: Any

### Issue description
`GooglePaymentCardNonce.isNetworkTokenized` is always `false` in sandbox, also for network tokenized cards.
The same card used in production has `GooglePaymentCardNonce.isNetworkTokenized = true`.

I don't know if this is the intended behavior, but it would be great to have the correct configuration also in sandbox.

**Comment by sarahkoop** [comment]
Hi @francescocervone thanks for using the Braintree Android SDK. Please [contact Support](https://help.braintreepayments.com/) with your merchant ID, they'll assist in troubleshooting your Google Pay sandbox integration.
